export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_API_SUCCESS = "GET_API_SUCCESS";
export const CREATE_API_SUCCESS = "CREATE_API_SUCCESS";
export const EDIT_API_SUCCESS = "EDIT_API_SUCCESS";
export const DELETE_API_SUCCESS = "DELETE_API_SUCCESS";
export const GET_API_DETAIL_SUCCESS = "GET_API_DETAIL_SUCCESS";
